openapi: 3.0.0
info:
  title: Jobs Api
  contact: {}
  version: '1.0'
servers:
- url: https://temp-job-service.onrender.com/api/v1
  variables: {}
paths:
  /login:
    post:
      tags:
      - auth
      summary: login
      operationId: login
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - email
              - password
              type: object
              properties:
                email:
                  type: string
                  example: testuser@test.com
                password:
                  type: integer
                  format: int32
                  example: 1234567
        required: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /update-user:
    patch:
      tags:
      - auth
      summary: update-user
      operationId: update-user
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - email
              - location
              - lastName
              - name
              type: object
              properties:
                email:
                  type: string
                  example: demo@test.com
                location:
                  type: string
                  example: india
                lastName:
                  type: string
                  example: what are you
                name:
                  type: string
                  example: fahmewbangladesh
        required: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  /register:
    post:
      tags:
      - auth
      summary: register
      operationId: register
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - name
              - email
              - password
              type: object
              properties:
                name:
                  type: string
                  example: demo
                email:
                  type: string
                  example: demo@test.com
                password:
                  type: integer
                  format: int32
                  example: 1234567
        required: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /jobs:
    get:
      tags:
      - jobs
      summary: list
      operationId: list
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    post:
      tags:
      - jobs
      summary: create
      operationId: create
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - company
              - position
              - jobLocation
              - jobType
              - status
              type: object
              properties:
                company:
                  type: string
                  example: apple
                position:
                  type: string
                  example: db123
                jobLocation:
                  type: string
                  example: Dhaka
                jobType:
                  type: string
                  example: full-time
                status:
                  type: string
                  example: inteview
        required: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  /jobs/stats:
    get:
      tags:
      - jobs
      summary: stats
      operationId: stats
      parameters:
      - name: page
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 1
      - name: jobType
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: intern
      - name: search
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: Community
      - name: sort
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: z-a
      - name: status
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: interview
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The jobs ID
    get:
      tags:
      - jobs
      summary: single
      operationId: single
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []

    patch:
      tags:
      - jobs
      summary: update
      operationId: update
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - company
              - position
              type: object
              properties:
                company:
                  type: string
                  example: fahreyad
                position:
                  type: string
                  example: fullstack123
        required: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []

    delete:
      tags:
      - jobs
      summary: delete
      operationId: delete
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
- name: auth
- name: jobs